language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"

branches:
  only:
  - master

install:
  - pip3 install coverage

script:
  - coverage run -m unittest discover
