language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"

branches:
  only:
  - master

install:
  - pip3 install coverage
  - pip3 install codecov

script:
  - coverage run -m unittest discover

after_success:
  - codecov
