language: python

jobs:
  include:
  - stage: 3.4 Test
    python: "3.4"
  - stage: 3.5 Test
    python: "3.5"
  - stage: 3.6 Test
    python: "3.6"
  - stage: 3.7 Test
    python: "3.7"

branches:
  only:
  - master

install:
  - pip install coverage
  - pip install codecov

script:
  - coverage run -m unittest discover

after_success:
  - codecov
